ini/asistencia/urls.py
from django.urls import path
from asistencia import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logueado/', views.logueado, name='logueado'),
    path('logout_views/', views.logout_views, name="logout_views"),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('persona/', views.persona, name='persona'),
    path('crear_persona/', views.crear_persona, name='crear_persona'),
    path('editar_persona/<int:id>', views.editar_persona, name='editar_persona'),
    path('eliminar_persona/<int:id>', views.eliminar_persona, name='eliminar_persona'),

    path('programa/', views.programa, name='programa'),
    path('crear_programa/', views.crear_programa, name="crear_programa"), 
    path('detalle_programas/<int:id>', views.detalle_programas, name="detalle_programas"),
    path('editar_programa/<int:id>', views.editar_programa, name="editar_programa"),
    path('eliminar_programa/<int:id>', views.eliminar_programa, name="eliminar_programa"),
    path('crear_modulo/<int:id>', views.crear_modulo, name="crear_modulo"),
    path('editar_modulo/<int:id>', views.editar_modulo, name="editar_modulo"),
    path('eliminar_modulo/<int:id>', views.eliminar_modulo, name="eliminar_modulo"),
    path('reporte_pdf/<int:programa_id>/', views.reporte_asistencia_pdf, name='reporte_asistencia_pdf'),
    path('inscripcion/', views.inscripcion, name='inscripcion'),
    
    path('inscripcion/seleccionar/', views.vista_seleccionar_programa, name='vista_seleccionar_programa'),
    path('inscripcion/guardar/<int:id>/', views.inscribir_programa, name='inscribir_programa'),

    path('asistencia/', views.asistencia, name='asistencia'),
    
    path('asistencia/registrar/<int:id>/', views.registrar_asistencia, name='registrar_asistencia'),
    path('asistencia/guardar/<int:id>/', views.guardar_asistencia, name='guardar_asistencia'),
]

ini/ini/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('asistencia.urls'))
]

ini/asistencia/models.py
from django.db import models
from django.contrib.auth.models import User 

class Programa(models.Model):
    nombre = models.CharField(max_length=200)
    codigo = models.CharField(max_length=100, unique=True) 
    estatus = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre

class Modulo(models.Model):
    programa = models.ForeignKey(Programa, on_delete=models.CASCADE, related_name='modulos') 
    nombre = models.CharField(max_length=200)
    fecha = models.DateField(null=True, blank=True)
    estatus = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.programa.nombre} - {self.nombre}"

class Inscripcion(models.Model):
    programa = models.ForeignKey(Programa, on_delete=models.CASCADE) 
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='inscripciones') 
    
    class Meta:
        unique_together = ('programa', 'usuario') 
        verbose_name_plural = "Inscripciones"

class Asistencia(models.Model):
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE)    
    modulo = models.ForeignKey(Modulo, on_delete=models.CASCADE, null=True, blank=True)
    asistio = models.BooleanField(default=False)
    def __str__(self):
        return f"Asistencia de {self.inscripcion.usuario.username} en {self.fecha}"
    
class datos_personales(models.Model):
    id_user = models.OneToOneField(User, on_delete=models.CASCADE)
    cedula = models.CharField(max_length=200)
    nombre = models.CharField(max_length=200)
    estatus = models.BooleanField(default=True)

ini/asistencia/views.py
from sqlite3 import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from asistencia import models
from django.contrib.auth.models import User

def eliminar_persona(request, id):
    
    usuario = User.objects.get(id=id)
    usuario_activo = models.Inscripcion.objects.filter(usuario = usuario) 
    if not usuario_activo.exists():
        
        u = models.datos_personales.objects.filter(id_user=usuario).delete()
        us = User.objects.filter(id=id).delete()
        print('usuario eliminado')
        return redirect('persona')

    else:
        print('el usuario no se puede eliminar porque tiene registros')
        return redirect('persona')


def eliminar_programa(request, id):
    
    usuario_activo = models.Inscripcion.objects.filter(programa = id) 
    if not usuario_activo.exists():
        usuario_activo.delete()
        print('programa eliminado')
        return redirect('editar_programa')

    else:
        print('el programa no se puede eliminar porque tiene registros')
        return redirect('programa')

def editar_programa(request, id):
    if request.method == 'POST':

        nombre = request.POST.get('nombre')
        codigo = request.POST.get('codigo')
        estatus = request.POST.get('estatus') 

        models.Programa.objects.filter(id=id).update(
            nombre = nombre,
            codigo = codigo,
            estatus = estatus 
        )
        print('programa editado correctamente ')

        return redirect('detalle_programas', id)
    else:
        programa = models.Programa.objects.get(id=id)
        return render (request, 'editar_programa.html', {'programa':programa})

def editar_modulo(request, id):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        fecha = request.POST.get('fecha')
        estatus = request.POST.get('estatus')

        models.Modulo.objects.filter(id=id).update(
            nombre = nombre,
            fecha = fecha,
            estatus = estatus,
        )
        return redirect('programa')
    else:
        modulo = models.Modulo.objects.get(id = id)
        print(modulo.fecha) 
        return render(request, 'editar_modulo.html', {'modulo':modulo})

def eliminar_modulo(request, id):
    usuario_activo = models.Asistencia.objects.filter(modulo = id) 
    for i in usuario_activo:
        print (f'esto es {i.modulo.nombre}')
    programa = models.Modulo.objects.get(id=id)
    modulos = models.Modulo.objects.filter(id=id)
    print(programa.programa.id)
    if not usuario_activo.exists():
        modulos.delete()
        print('modulo eliminado')
        return redirect('detalle_programas', programa.programa.id)

    else:
        print('el modulo no se puede eliminar porque tiene registros')
        return redirect('programa')

def logout_views(request):
    logout(request)
    return redirect('index')

def logueado(request):
    if request.method == 'POST':
        try:
            user = request.POST.get('nombre')
            contrasena = request.POST.get('pasword')

            print(f'{user} {contrasena}')

            usuario = authenticate(request, username=user, password=contrasena)

            if usuario is not None:
                login(request, usuario)
                print('logueado con éxito')

                # ✅ Captura el parámetro next
                persona = models.datos_personales.objects.all() 
                personas_max = len(persona)
                programa = models.Programa.objects.all()
                programa_max = len(programa)
                next_url = request.GET.get('next') or request.POST.get('next') or 'dashboard'
                if next_url == 'dashboard':
                    print(f' personas maximas {personas_max}')
                    return render(request, 'dashboard.html', {'personas':personas_max,
                                                              'programa_max': programa_max})
                return redirect(next_url)
            else:
                print('error al loguear')
                return redirect('index')
        except Exception as e:
            print(f'el error es {e}')
            return redirect('index')
    else:
        return redirect('index')
    
def index(request):
    return render(request, 'index.html')

@login_required
def dashboard(request):
    persona = models.datos_personales.objects.all() 
    personas_max = len(persona)
    programa = models.Programa.objects.filter(estatus=True)
    programa_max = len(programa)
    return render(request, 'dashboard.html', {'personas':personas_max,
                                              'programa_max': programa_max})

def crear_programa(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        codigo = request.POST.get('codigo')

        models.Programa(
            nombre = nombre,
            codigo = codigo,
        ).save()

        print('programa guardado')
        return redirect('crear_programa')
    else:
        return render(request, 'crear_programa.html')

def programa(request):
    programas = models.Programa.objects.all()
    return render(request, 'modulo_programa.html', {'programas' : programas})



def detalle_programas (request, id):
    programa = models.Programa.objects.get(id=id)
    modulos_prograsma = models.Modulo.objects.filter(programa = id)
    return render (request, 'detalle_programas.html', {'programa':programa,
                                                       'modulos':modulos_prograsma})

def crear_modulo(request, id):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        fecha = request.POST.get('fecha')
        prograam = models.Programa.objects.get(id=id)
        models.Modulo(
            programa = prograam,
            nombre = nombre,
            fecha = fecha,
        ).save()
        print('modulo guardado correctamente')
        return redirect('detalle_programas', id)
    else:
        programa_sujeto = models.Programa.objects.get(id=id)
        print(programa_sujeto.nombre, programa_sujeto.id)
        return render(request, 'nuevo_modulo.html', {'programa_id':programa_sujeto})

def inscripcion(request): 
    inscripciones = models.Inscripcion.objects.filter()
    for i in inscripciones:
        print(i.usuario.datos_personales.nombre) 
    return render(request, 'modulo_inscripcion.html', {'inscripciones': inscripciones})

def vista_seleccionar_programa(request):
    programas = models.Programa.objects.all()
    
    return render(request, 'inscribir.html', {'programas': programas})

def asistencia(request):
    programas = models.Programa.objects.all()
    return render(request, 'asistencia.html', {'programas': programas})

# views.py (Función registrar_asistencia)

def registrar_asistencia(request, id):
    modulo = get_object_or_404(models.Modulo, id=id)
    
    # 1. Obtenemos todos los inscritos en el programa del módulo
    inscritos = models.Inscripcion.objects.filter(programa=modulo.programa)
    
    lista_asistencia = []
    
    # 2. Iteramos sobre los inscritos para determinar su estado
    for inscripcion in inscritos:
        
        # Intentamos obtener la asistencia previamente guardada para este estudiante Y este módulo
        try:
            asistencia_guardada = models.Asistencia.objects.get(
                inscripcion=inscripcion, 
                modulo=modulo
            )
            # Si existe, usamos el valor guardado
            asistio_estado = asistencia_guardada.asistio
            
        except models.Asistencia.DoesNotExist:
            # Si NO existe, asumimos el estado por defecto: TRUE (Asistió)
            asistio_estado = True 
            
        lista_asistencia.append({
            'inscripcion_id': inscripcion.id,
            # Ahora podemos acceder al nombre de la persona gracias al OneToOneField corregido:
            'nombre_completo': inscripcion.usuario.datos_personales.nombre, 
            'cedula': inscripcion.usuario.datos_personales.cedula,
            'asistio': asistio_estado, # True o False
        })
    
    context = {
        'modulo': modulo,
        'programa': modulo.programa,
        'lista_asistencia': lista_asistencia # Enviamos la lista procesada
    }
    return render(request, 'registrar_asistencia.html', context)

# 3. Guardar la Asistencia (Lógica del botón Guardar)
def guardar_asistencia(request, id):
    modulo = get_object_or_404(models.Modulo, id=id)
    
    if request.method == 'POST':
        inscritos = models.Inscripcion.objects.filter(programa=modulo.programa)
        
        for inscripcion in inscritos:
            # El checkbox se llama "asistencia_ID"
            checkbox_name = f'asistencia_{inscripcion.id}'
            # Si está marcado devuelve 'on', si no devuelve None
            presente = request.POST.get(checkbox_name) == 'on'
            
            # Guardamos o actualizamos la asistencia
            models.Asistencia.objects.update_or_create(
                inscripcion=inscripcion,
                modulo=modulo,
                defaults={'asistio': presente} 
            )
            
        print("Asistencias guardadas")
        return redirect('asistencia') # Volvemos al panel principal

    return redirect('asistencia')

def inscribir_programa(request, id):
    programa_seleccionado = get_object_or_404(models.Programa, id=id)

    if request.method == 'POST':
        try:
            usuario_id = request.POST.get('usuario_id')
            
            usuario_obj = User.objects.get(id=usuario_id)
            

ini/templates/crear_programa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Nuevo Programa</title>
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar" id="sidebar">
        <div class="close-menu-btn" id="close-menu">
            <i class="fas fa-times"></i>
        </div>
        <a href="{% url 'dashboard' %}" class="dashboard">
            <div class="logo">
                <i class="fas fa-calendar-check"></i> 
                <h2>ASISTENCIA APP</h2>
            </div>
        </a>
        <nav class="nav-links">
            <a href="{% url 'persona' %}" class="nav-item">
                <i class="fas fa-users"></i>
                <span>Gestión de Personas</span>
            </a>
            <a href="{% url 'programa' %}" class="nav-item active">
                <i class="fas fa-graduation-cap"></i>
                <span>Programas y Módulos</span>
            </a>
            <a href="{% url 'inscripcion' %}" class="nav-item">
                <i class="fas fa-user-plus"></i>
                <span>Inscripciones</span>
            </a>
            <a href="{% url 'asistencia' %}" class="nav-item ">
                <i class="fas fa-clipboard-list"></i>
                <span>Registro de Asistencias</span>
            </a>
    </div>
    <div class="menu-overlay" id="menu-overlay"></div>
    <div class="main-content">
        <header class="header">
            <button class="menu-toggle" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>
            <h1>Crear Programa</h1>
            <div class="user-info">Administrador</div>
        </header>

        <section class="content-area form-area">
            <div class="form-card">
                <h3>Registro de Programa Educativo</h3>
                
                <form action="{% url 'crear_programa' %}" method="POST" class="crud-form">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_nombre"><i class="fas fa-file-signature"></i> Nombre del Programa</label>
                        <input id="id_nombre" name="nombre" type="text" placeholder="Ej: Diplomado en Desarrollo Web" class="form-field" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="id_codigo"><i class="fas fa-barcode"></i> Código Único</label>
                        <input id="id_codigo" type="text" name="codigo" placeholder="Ej: DWEB-2024" class="form-field" required>
                    </div>

                    <div class="form-actions">
                        <a href="{% url 'programa' %}" class="btn-secondary"><i class="fas fa-arrow-left"></i> Cancelar</a>
                        <button type="submit" class="btn-primary"><i class="fas fa-save"></i> Guardar Programa</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
    <script src="{% static 'js/menu.js' %}" ></script>

</body>
</html>

ini/templates/editar_modulo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Modulo</title>
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar" id="sidebar">
        <div class="close-menu-btn" id="close-menu">
            <i class="fas fa-times"></i>
        </div>
        <a href="{% url 'dashboard' %}" class="dashboard">
            <div class="logo">
                <i class="fas fa-calendar-check"></i> 
                <h2>ASISTENCIA APP</h2>
            </div>
        </a>
        <nav class="nav-links">
            <a href="{% url 'persona' %}" class="nav-item">
                <i class="fas fa-users"></i>
                <span>Gestión de Personas</span>
            </a>
            <a href="{% url 'programa' %}" class="nav-item active">
                <i class="fas fa-graduation-cap"></i>
                <span>Programas y Módulos</span>
            </a>
            <a href="{% url 'inscripcion' %}" class="nav-item">
                <i class="fas fa-user-plus"></i>
                <span>Inscripciones</span>
            </a>
            <a href="{% url 'asistencia' %}" class="nav-item ">
                <i class="fas fa-clipboard-list"></i>
                <span>Registro de Asistencias</span>
            </a>
    </div>
    <div class="menu-overlay" id="menu-overlay"></div>
    <div class="main-content">
        <header class="header">
            <button class="menu-toggle" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>
            <h1>Editar Modulo</h1>
            <div class="user-info">Administrador</div>
        </header>

        <section class="content-area form-area">
            <div class="form-card">
                <h3>Detalles de la Persona</h3>
                <form action="{% url 'editar_modulo' modulo.id %}" method="POST" class="crud-form">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_nombre"><i class="fas fa-user"></i> Nombre del modulo</label>
                        <input id="id_nombre" type="text" name="nombre" value="{{ modulo.nombre }}" class="form-field" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="id_fecha"><i class="fas fa-calendar-alt"></i> Fecha de Inicio/Creación</label>
                        <input id="id_fecha" type="date" name="fecha" class="form-field" required value="{{modulo.fecha|date:'Y-m-d'}}"> 
                    </div>

                    <div class="form-group">
                        <label for="id_estatus"><i class="fas fa-toggle-on"></i> Estatus</label>
                        <select id="id_estatus" name="estatus" class="form-field">
                            {% if modulo.estatus %}
                                <option value="1" selected>Activo</option>
                                <option value="0">Inactivo</option>
                            {% else %}
                                <option value="0" selected>Inactivo</option>
                                <option value="1">Activo</option>
                            {% endif %} 
                        </select>
                    </div>
                    
                    <input type="hidden" name="persona_id" value="{{ usuario.id_user.id }}">
                    
                    <div class="form-actions">
                        <button type="submit" class="btn-primary"><i class="fas fa-save"></i> Guardar Cambios</button>
                        <a href="{% url 'eliminar_modulo' modulo.id %}" class="btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
                    </div>
                </form>
            </div>
        </section>
    </div>
    <script src="{% static 'js/menu.js' %}" ></script>

</body>
</html>

ini/templates/editar_persona.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Persona</title>
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar" id="sidebar">
        <div class="close-menu-btn" id="close-menu">
            <i class="fas fa-times"></i>
        </div>
        <a href="{% url 'dashboard' %}" class="dashboard">
            <div class="logo">
                <i class="fas fa-calendar-check"></i> 
                <h2>ASISTENCIA APP</h2>
            </div>
        </a>
        <nav class="nav-links">
            <a href="{% url 'persona' %}" class="nav-item active">
                <i class="fas fa-users"></i>
                <span>Gestión de Personas</span>
            </a>
            <a href="{% url 'programa' %}" class="nav-item">
                <i class="fas fa-graduation-cap"></i>
                <span>Programas y Módulos</span>
            </a>
            <a href="{% url 'inscripcion' %}" class="nav-item">
                <i class="fas fa-user-plus"></i>
                <span>Inscripciones</span>
            </a>
            <a href="{% url 'asistencia' %}" class="nav-item ">
                <i class="fas fa-clipboard-list"></i>
                <span>Registro de Asistencias</span>
            </a>
    </div>
    <div class="menu-overlay" id="menu-overlay"></div>
    <div class="main-content">
        <header class="header">
            <button class="menu-toggle" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>
            <h1>Editar Persona</h1>
            <div class="user-info">Administrador</div>
        </header>

        <section class="content-area form-area">
            <div class="form-card">
                <h3>Detalles de la Persona</h3>
                <form action="{% url 'editar_persona' usuario.id_user.id %}" method="POST" class="crud-form">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_nombre"><i class="fas fa-user"></i> Nombre de Usuario</label>
                        <input id="id_nombre" type="text" name="nombre" value="{{ usuario.nombre }}" class="form-field" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="id_cedula"><i class="fas fa-id-card"></i> Cédula</label>
                        <input id="id_cedula" type="text" name="cedula" value="{{ usuario.cedula }}" class="form-field" required>
                    </div>

                    <div class="form-group">
                        <label for="id_estatus"><i class="fas fa-toggle-on"></i> Estatus</label>
                        <select id="id_estatus" name="estatus" class="form-field">
                            {% if usuario.estatus %}
                                <option value="1" selected>Activo</option>
                                <option value="0">Inactivo</option>
                            {% else %}
                                <option value="0" selected>Inactivo</option>
                                <option value="1">Activo</option>
                            {% endif %} 
                        </select>
                    </div>
                    
                    <input type="hidden" name="persona_id" value="{{ usuario.id_user.id }}">
                    
                    <div class="form-actions">
                        <button type="submit" class="btn-primary"><i class="fas fa-save"></i> Guardar Cambios</button>
                        <a href="{% url 'eliminar_persona' usuario.id_user.id %}" class="btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
                    </div>
                </form>
            </div>
        </section>
    </div>
        <script src="{% static 'js/menu.js' %}" ></script>

</body>
</html>

ini/templates/editar_programa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Programa</title>
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar" id="sidebar">
        <div class="close-menu-btn" id="close-menu">
            <i class="fas fa-times"></i>
        </div>
        <a href="{% url 'dashboard' %}" class="dashboard">
            <div class="logo">
                <i class="fas fa-calendar-check"></i> 
                <h2>ASISTENCIA APP</h2>
            </div>
        </a>
        <nav class="nav-links">
            <a href="{% url 'persona' %}" class="nav-item">
                <i class="fas fa-users"></i>
                <span>Gestión de Personas</span>
            </a>
            <a href="{% url 'programa' %}" class="nav-item active">
                <i class="fas fa-graduation-cap"></i>
                <span>Programas y Módulos</span>
            </a>
            <a href="{% url 'inscripcion' %}" class="nav-item">
                <i class="fas fa-user-plus"></i>
                <span>Inscripciones</span>
            </a>
            <a href="{% url 'asistencia' %}" class="nav-item ">
                <i class="fas fa-clipboard-list"></i>
                <span>Registro de Asistencias</span>
            </a>
    </div>
    <div class="menu-overlay" id="menu-overlay"></div>
    <div class="main-content">
        <header class="header">
            <button class="menu-toggle" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>
            <h1>Editar Programa</h1>
            <div class="user-info">Administrador</div>
        </header>

        <section class="content-area form-area">
            <div class="form-card">
                <h3>Detalles de la Persona</h3>
                <form action="{% url 'editar_programa' programa.id %}" method="POST" class="crud-form">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="id_nombre"><i class="fas fa-user"></i> Nombre del programa</label>
                        <input id="id_nombre" type="text" name="nombre" value="{{ programa.nombre }}" class="form-field" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="id_cedula"><i class="fas fa-id-card"></i> Codigo</label>
                        <input id="id_cedula" type="text" name="codigo" value="{{ programa.codigo }}" class="form-field" required>
                    </div>

                    <div class="form-group">
                        <label for="id_estatus"><i class="fas fa-toggle-on"></i> Estatus</label>
                        <select id="id_estatus" name="estatus" class="form-field">
                            {% if programa.estatus %}
                                <option value="1" selected>Activo</option>
                                <option value="0">Inactivo</option>
                            {% else %}
                                <option value="0" selected>Inactivo</option>
                                <option value="1">Activo</option>
                            {% endif %} 
                        </select>
                    </div>
                    
                    <input type="hidden" name="persona_id" value="{{ usuario.id_user.id }}">
                    
                    <div class="form-actions">
                        <button type="submit" class="btn-primary"><i class="fas fa-save"></i> Guardar Cambios</button>
                        <a href="{% url 'eliminar_programa' programa.id %}" class="btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
                    </div>
                </form>
            </div>
        </section>
    </div>
        <script src="{% static 'js/menu.js' %}" ></script>

</body>
</html>

ini/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesión</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <section class="login-hero">
    <div class="login-card">
      <div class="login-subtitle">BIENVENIDO AL</div>
      <h1 class="login-title">INICIO DE SESIÓN</h1>
      <form class="login-form" action="{% url 'logueado' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
          <i class="fas fa-user"></i>
          <input id="user" type="text" class="field" name="nombre" placeholder="Ingresa tu usuario" required>
        </div>
        <div class="input-group">
          <i class="fas fa-lock"></i>
          <input id="pass" type="password" name="pasword" class="field" placeholder="Ingresa tu contraseña" required>
          <i class="fas fa-eye icon-password" onclick="togglePassword()"></i>
        </div>
        <button type="submit" class="btn-primary">Acceder</button>
      </form>
    </div>
    </section>

    <script>
        function togglePassword() {
      var passField = document.getElementById('pass');
      var icon = document.querySelector('.icon-password'); // Selecciono por la clase más específica
      if (passField.type === "password") {
        passField.type = "text";
        icon.classList.replace('fa-eye', 'fa-eye-slash');
      } else {
        passField.type = "password";
        icon.classList.replace('fa-eye-slash', 'fa-eye');
      }
    }
      </script>
      
</body>
</html>